import Head from "next/head";
import { GetStaticProps } from "next/types";

type Article = {
  id: number;
  title: string;
  body: string;
};

type HomeProps = {
  articles: Article[];
};

export default function Home({ articles }: HomeProps) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        {articles.map((article) => (
          <div key={article.id}>
            <h3>{article.title}</h3>
          </div>
        ))}
      </div>
    </>
  );
}

export const getStaticProps = async () => {
  const resp = await fetch(
    `https://jsonplaceholder.typicode.com/posts?_limit=6`
  );
  const articles = await resp.json();

  return {
    props: {
      articles,
    },
  };
};
